"""Add active column to project model.

Revision ID: 2b6af880739
Revises: 5994fc9e9755
Create Date: 2015-12-09 23:27:53.228609

"""

# revision identifiers, used by Alembic.
revision = '2b6af880739'
down_revision = '5994fc9e9755'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('active', sa.Boolean(), default=True, nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'active')
    ### end Alembic commands ###
