"""empty message

Revision ID: 5994fc9e9755
Revises: 1f575ffb0485
Create Date: 2015-10-29 18:15:46.407217

"""

# revision identifiers, used by Alembic.
revision = '5994fc9e9755'
down_revision = '1f575ffb0485'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    ### end Alembic commands ###
